/**
 * @author flying
 * Color Palette by Color Scheme Designer
 * Palette URL: http://colorschemedesigner.com/#0021Tw0w0w0w0
 */
/*Primary Color:*/

var pc1 = "#FF0000";
var pc1rgb = rgb(255, 0, 0);

var pc2 = "#BF3030";
var pc2rgb = rgb(191, 48, 48);

var pc3 = "#A60000";
var pc3rgb = rgb(166, 0, 0);

var pc4 = "#FF4040";
var pc4rgb = rgb(255, 64, 64);

var pc5 = "#FF7373";
var pc5rgb = rgb(255, 115, 115);

/* Complementary Color:*/

var cc1 = "#00CC00";
var cc1rgb = rgb(0, 204, 0);

var cc2 = "#269926";
var cc2rgb = rgb(38, 153, 38);

var cc3 = "#008500";
var cc3rgb = rgb(0, 133, 0);

var cc4 = "#39E639";
var cc4rgb = rgb(57, 230, 57);

var cc5 = "#67E667";
var cc5rgb = rgb(103, 230, 103);


/*Generated by Color Scheme Designer © Petr Stanicek 2002-2009*/
